services:
  backend:
    build:
      context: ./
    ports:
      - "8080:8080"
    environment:
      # change dev or prod to use different profiles (application.porperties profiles)
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network

  frontend:
    build:
      context: ./vue
    ports:
      - "5173:80" # Maps Nginx port 80 to localhost:5173
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
